#!/usr/bin/env python3

import matplotlib.pyplot as plt
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from scipy.fftpack import fft,ifft,ifftn
from scipy import signal

def convert_raw(filename):
    def converter(s):
        return int(s, 16)
    y = np.loadtxt(filename, converters={0: converter})
    np.savetxt('hr-good.txt', y[225000:245000], '%d')

def show(filename):
    y = np.loadtxt(filename)
    N = len(y)
    F = (57600 / 40)
    T = 1.0 / F
    x = np.linspace(0.0, N*T, N)
    xf = np.linspace(0.0, 1.0/(2.0*T), N/2)
    
    yconst = signal.detrend(y, type='constant')
    ylin = signal.detrend(y, type='linear')

    plt.plot(x, y, '-rx')
    plt.plot(x, yconst, '-bo')
    plt.plot(x, ylin, '-k+')

    plt.grid()
    plt.legend(['signal', 'const. detrend', 'linear detrend'])
    plt.show()

if __name__ == '__main__':
    #convert_raw('/home/rush/workspace/arduino/HeartRate/hr.txt')
    show('/home/rush/workspace/arduino/HeartRate/hr-good.txt')
